# Generated by Django 5.0.14 on 2025-11-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_questionpaper_is_private_link_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersection',
            name='weightage',
            field=models.FloatField(default=0.0, help_text='Weightage percentage for this section'),
        ),
    ]
